name: Auto-label PLYNK submissions
on:
  issues:
    types: [opened, reopened, edited]

permissions:
  issues: write            # lets the workflow add labels

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // 1. read the hidden line
            const body  = context.payload.issue.body || '';
            const match = body.match(/PLYNK-LABELS:\s*([^\-]*)/i);
            const labels = match ? match[1].split(',').map(l => l.trim()) : [];

            // 2. add them
            if (labels.length) {
              await github.issues.addLabels({
                ...context.repo,
                issue_number: context.payload.issue.number,
                labels
              });
            }
