name: Auto-label PLYNK submissions
on:
  issues:
    types: [opened, reopened, edited]

permissions:
  issues: write   # workflow can add labels

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Parse hidden label list
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            // Grab everything between <!-- PLYNK-LABELS: ... -->
            const body  = context.payload.issue.body || '';
            const match = body.match(/<!--\s*PLYNK-LABELS:\s*([^>]*)-->/i);
            const labels = match ? match[1].split(',').map(l => l.trim()).filter(Boolean) : [];
            core.setOutput('labels', JSON.stringify(labels));

      - name: Apply labels
        if: steps.parse.outputs.labels != '[]'
        uses: actions/github-script@v7
        env:
          LABELS: ${{ steps.parse.outputs.labels }}
        with:
          script: |
            const labels = JSON.parse(process.env.LABELS);
            if (!labels.length) return;

            await github.request(
              'POST /repos/{owner}/{repo}/issues/{issue_number}/labels',
              {
                owner: context.repo.owner,
                repo:  context.repo.repo,
                issue_number: context.issue.number,
                labels
              }
            );
